In [ ]:
import pandas as pd

3.0.3


In [2]:
#1) Replace NaN with 0 and interchange rows and columns

import numpy as np

arr = np.array([[6, -8, 73, -110],
                [np.nan, -8, 0, 94]])

# Replace NaN with 0
arr = np.nan_to_num(arr, nan=0)

print("After replacing NaN with 0:")
print(arr)

# Interchange rows and columns (Transpose)
transposed = arr.T

print("\nAfter interchanging rows and columns:")
print(transposed)

After replacing NaN with 0:
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

After interchanging rows and columns:
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [3]:
# 2) Move axes of a 3D array to new positions
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [10, 11, 12]]])
# Move axes to new positions
moved_axes = np.moveaxis(arr_3d, [0, 1, 2], [2, 0, 1])
print("\nAfter moving axes of the 3D array:")
print(moved_axes)


After moving axes of the 3D array:
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [4]:
# 3) Replace NaN values with average of columns
arr = np.array([[1, 2, np.nan],
                         [4, np.nan, 6],
                         [7, 8, 9]])
# Calculate column means, ignoring NaN
col_means = np.nanmean(arr, axis=0)
# Replace NaN with column means
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_means, inds[1])
print("\nResult:")
print(arr)



Result:
[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [5]:
 # 4) Replace negative values with zero
arr = np.array([[1, -2, 3],
                         [-4, 5, -6],
                         [7, -8, 9]])
# Replace negative values with zero
arr[arr < 0] = 0
print("\nResult:")
print(arr)


Result:
[[1 0 3]
 [0 5 0]
 [7 0 9]]
